baseurl: '/'
permalink: pretty
title: 'Tall Trees Construction'

logo:
  mobile: "images/logo/house_32dp_DA954B_FILL0_wght400_GRAD0_opsz40.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/TallTreesLogo.png"
  desktop_height: "21px"
  desktop_width: "160px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  events:
    output: true
    sort_by: weight
  classes:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "home"
    values:
      layout: "home"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "services"
  - scope:
      path: ""
      type: "contact"
    values:
      layout: "contact"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
