# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tall Trees Construction
email: talltreesconstruction@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  test for business.
baseurl: /Tall-Trees-Construction # the subpath of your site, e.g. /blog
url: https://orion-miller.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Tall Trees Construction
address_line: Department of Biomedical Engineering, City University of Hong Kong, Rm. Y1411, 83 Tat Chee Avenue, Kowloon
# telephone_number: coming soon
company_email: talltreesconstruction@gmail.com
google_maps: coming soon
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3690.466345131139!2d114.17065757485784!3d22.336013641600886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404073400f3ef35%3A0xb13b4355bdf28a9d!2z6aaZ5riv5Z-O5biC5aSn5a245qWK5bu65paH5a246KGT5qiT!5e0!3m2!1szh-TW!2shk!4v1671523242854!5m2!1szh-TW!2shk


# Social Link
facebook_link: http://www.facebook.com
# twitter_link: http://www.twitter.com
# linkedin_link: http://www.linkedin.com
# googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
